"""updating table events

Revision ID: 09c5ab4cc81f
Revises: ba3cf4d84a41
Create Date: 2024-11-25 00:00:02.608226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c5ab4cc81f'
down_revision: Union[str, None] = 'ba3cf4d84a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('location', sa.String(), nullable=False))
    op.add_column('Events', sa.Column('date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'date')
    op.drop_column('Events', 'location')
    # ### end Alembic commands ###
